### ISSUE TITLE
An error occurred while communicating with the data source

### ISSUE THREAD

**Issue by Mimi2611** [ParFlesh/zabbix-wdc#6]
Hi,

When i triy to connect the web data connector to zabbix, i have this error.

![image](https://user-images.githubusercontent.com/6419704/88775846-81fe3e80-d185-11ea-8443-e7dcaedb41dd.png)

Can you please help me?

Regards,

Marine

**Comment by ParFlesh** [comment]
That error is caused by the web data connector being unable to connect to the URL.  

Verify that you are able to connect to the API URL.

**Comment by Mimi2611** [comment]
This seems that i can. Is there anything to configure on Zabbix?
![image](https://user-images.githubusercontent.com/6419704/88810292-7b87bb00-d1b5-11ea-9950-762add974ba0.png)

**Comment by ParFlesh** [comment]
Can you test using the [WDC SDK](https://tableau.github.io/webdataconnector/)?

Also, are you using basic auth or an external authentication?

**Comment by Mimi2611** [comment]
I will test with the SDK. I use basic auth.

**Comment by Mimi2611** [comment]
With the Web Data connector, it's working

**Comment by ParFlesh** [comment]
It looks like the error reporting mechanism needs a little work, I am going to fix that then we should better be able to see what error you are recieving.

**Comment by Mimi2611** [comment]
OK thanks. Tell me when you have finished.

**Comment by ParFlesh** [comment]
I was able to get the error reporting updated to include better output.

I was also able to track down the cause of your error.

Looks like `Access-Control-Allow-Headers` needs to include `Content-Type` header, so that javascript is able to send the header which is required for all calls to the api.

`Failed to load https://zabbix.softcom.pro/api_jsonrpc.php: Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by ParFlesh** [comment]
Also, in case you would like to be able to debug when using tableau desktop here is the link to debug web data connectors using chromium.

https://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debug-chrome

**Comment by Mimi2611** [comment]
This working with the Access-Control-Allow_headers. Thank you very much for your help
